// Test barrel file for all HTML elements
// This file imports all element tests for easy execution

import 'a_test.dart' as a_test;
import 'abbr_test.dart' as abbr_test;
import 'address_test.dart' as address_test;
import 'area_test.dart' as area_test;
import 'article_test.dart' as article_test;
import 'aside_test.dart' as aside_test;
import 'audio_test.dart' as audio_test;
import 'b_test.dart' as b_test;
import 'base_test.dart' as base_test;
import 'bdi_test.dart' as bdi_test;
import 'bdo_test.dart' as bdo_test;
import 'blockquote_test.dart' as blockquote_test;
import 'body_test.dart' as body_test;
import 'br_test.dart' as br_test;
import 'button_test.dart' as button_test;
import 'canvas_test.dart' as canvas_test;
import 'caption_test.dart' as caption_test;
import 'cite_test.dart' as cite_test;
import 'code_test.dart' as code_test;
import 'col_test.dart' as col_test;
import 'colgroup_test.dart' as colgroup_test;
import 'data_test.dart' as data_test;
import 'datalist_test.dart' as datalist_test;
import 'db_test.dart' as db_test;
import 'del_test.dart' as del_test;
import 'details_test.dart' as details_test;
import 'dfn_test.dart' as dfn_test;
import 'dialog_test.dart' as dialog_test;
import 'div_test.dart' as div_test;
import 'dl_test.dart' as dl_test;
import 'dt_test.dart' as dt_test;
import 'em_test.dart' as em_test;
import 'embed_test.dart' as embed_test;
import 'fieldset_test.dart' as fieldset_test;
import 'figcaption_test.dart' as figcaption_test;
import 'figure_test.dart' as figure_test;
import 'footer_test.dart' as footer_test;
import 'form_test.dart' as form_test;
import 'h1_test.dart' as h1_test;
import 'h2_test.dart' as h2_test;
import 'h3_test.dart' as h3_test;
import 'h4_test.dart' as h4_test;
import 'h5_test.dart' as h5_test;
import 'h6_test.dart' as h6_test;
import 'head_test.dart' as head_test;
import 'header_test.dart' as header_test;
import 'hgroup_test.dart' as hgroup_test;
import 'hr_test.dart' as hr_test;
import 'html_test.dart' as html_test;
import 'i_test.dart' as i_test;
import 'iframe_test.dart' as iframe_test;
import 'img_test.dart' as img_test;
import 'input_test.dart' as input_test;
import 'ins_test.dart' as ins_test;
import 'kbd_test.dart' as kbd_test;
import 'label_test.dart' as label_test;
import 'legend_test.dart' as legend_test;
import 'li_test.dart' as li_test;
import 'link_test.dart' as link_test;
import 'main_test.dart' as main_test;
import 'map_test.dart' as map_test;
import 'mark_test.dart' as mark_test;
import 'math_test.dart' as math_test;
import 'menu_test.dart' as menu_test;
import 'meta_test.dart' as meta_test;
import 'meter_test.dart' as meter_test;
import 'nav_test.dart' as nav_test;
import 'noscript_test.dart' as noscript_test;
import 'object_test.dart' as object_test;
import 'ol_test.dart' as ol_test;
import 'optgroup_test.dart' as optgroup_test;
import 'option_test.dart' as option_test;
import 'output_test.dart' as output_test;
import 'p_test.dart' as p_test;
import 'picture_test.dart' as picture_test;
import 'pre_test.dart' as pre_test;
import 'progress_test.dart' as progress_test;
import 'q_test.dart' as q_test;
import 'rp_test.dart' as rp_test;
import 'rt_test.dart' as rt_test;
import 'ruby_test.dart' as ruby_test;
import 's_test.dart' as s_test;
import 'samp_test.dart' as samp_test;
import 'script_test.dart' as script_test;
import 'search_test.dart' as search_test;
import 'section_test.dart' as section_test;
import 'select_test.dart' as select_test;
import 'slot_test.dart' as slot_test;
import 'small_test.dart' as small_test;
import 'source_test.dart' as source_test;
import 'span_test.dart' as span_test;
import 'strong_test.dart' as strong_test;
import 'style_test.dart' as style_test;
import 'sub_test.dart' as sub_test;
import 'summary_test.dart' as summary_test;
import 'sup_test.dart' as sup_test;
import 'svg_test.dart' as svg_test;
import 'table_test.dart' as table_test;
import 'tbody_test.dart' as tbody_test;
import 'td_test.dart' as td_test;
import 'template_test.dart' as template_test;
import 'textarea_test.dart' as textarea_test;
import 'tfoot_test.dart' as tfoot_test;
import 'th_test.dart' as th_test;
import 'thead_test.dart' as thead_test;
import 'time_test.dart' as time_test;
import 'title_test.dart' as title_test;
import 'tr_test.dart' as tr_test;
import 'track_test.dart' as track_test;
import 'u_test.dart' as u_test;
import 'ul_test.dart' as ul_test;
import 'video_test.dart' as video_test;
import 'wbr_test.dart' as wbr_test;

void main() {
  // Import all element tests
  a_test.main();
  abbr_test.main();
  address_test.main();
  area_test.main();
  article_test.main();
  aside_test.main();
  audio_test.main();
  b_test.main();
  base_test.main();
  bdi_test.main();
  bdo_test.main();
  blockquote_test.main();
  body_test.main();
  br_test.main();
  button_test.main();
  canvas_test.main();
  caption_test.main();
  cite_test.main();
  code_test.main();
  col_test.main();
  colgroup_test.main();
  data_test.main();
  datalist_test.main();
  db_test.main();
  del_test.main();
  details_test.main();
  dfn_test.main();
  dialog_test.main();
  div_test.main();
  dl_test.main();
  dt_test.main();
  em_test.main();
  embed_test.main();
  fieldset_test.main();
  figcaption_test.main();
  figure_test.main();
  footer_test.main();
  form_test.main();
  h1_test.main();
  h2_test.main();
  h3_test.main();
  h4_test.main();
  h5_test.main();
  h6_test.main();
  head_test.main();
  header_test.main();
  hgroup_test.main();
  hr_test.main();
  html_test.main();
  i_test.main();
  iframe_test.main();
  img_test.main();
  input_test.main();
  ins_test.main();
  kbd_test.main();
  label_test.main();
  legend_test.main();
  li_test.main();
  link_test.main();
  main_test.main();
  map_test.main();
  mark_test.main();
  math_test.main();
  menu_test.main();
  meta_test.main();
  meter_test.main();
  nav_test.main();
  noscript_test.main();
  object_test.main();
  ol_test.main();
  optgroup_test.main();
  option_test.main();
  output_test.main();
  p_test.main();
  picture_test.main();
  pre_test.main();
  progress_test.main();
  q_test.main();
  rp_test.main();
  rt_test.main();
  ruby_test.main();
  s_test.main();
  samp_test.main();
  script_test.main();
  search_test.main();
  section_test.main();
  select_test.main();
  slot_test.main();
  small_test.main();
  source_test.main();
  span_test.main();
  strong_test.main();
  style_test.main();
  sub_test.main();
  summary_test.main();
  sup_test.main();
  svg_test.main();
  table_test.main();
  tbody_test.main();
  td_test.main();
  template_test.main();
  textarea_test.main();
  tfoot_test.main();
  th_test.main();
  thead_test.main();
  time_test.main();
  title_test.main();
  tr_test.main();
  track_test.main();
  u_test.main();
  ul_test.main();
  video_test.main();
  wbr_test.main();
}
