name: dart_frog_html
description: A package that helps make html for Dart Frog servers.
version: 0.0.1
homepage: https://github.com/mtwichel/dart_frog_html
repository: https://github.com/mtwichel/dart_frog_html
issue_tracker: https://github.com/mtwichel/dart_frog_html/issues
documentation: https://github.com/mtwichel/dart_frog_html/blob/main/README.md

environment:
  sdk: ^3.0.0

dependencies:
  dart_frog: ^1.2.1

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^9.0.0
