import 'package:dart_frog_html/dart_frog_html.dart';

class A extends HtmlElement {
  A({
    Map<String, String>? attributes,
    super.children,
    super.className,
    super.id,
    super.accesskey,
    super.contenteditable,
    super.contextmenu,
    super.data,
    super.dir,
    super.draggable,
    super.dropzone,
    super.hidden,
    super.lang,
    super.spellcheck,
    super.style,
    super.tabindex,
    super.title,
    String? href,
    String? target,
    String? rel,
    String? hreflang,
    String? type,
  }) : super(
          'a',
          attributes: <String, String>{
            if (className != null) 'class': className,
            if (id != null) 'id': id,
            if (accesskey != null) 'accesskey': accesskey,
            if (contenteditable != null) 'contenteditable': contenteditable,
            if (contextmenu != null) 'contextmenu': contextmenu,
            if (data != null) 'data-*': data,
            if (dir != null) 'dir': dir,
            if (draggable != null) 'draggable': draggable,
            if (dropzone != null) 'dropzone': dropzone,
            if (hidden != null) 'hidden': hidden,
            if (lang != null) 'lang': lang,
            if (spellcheck != null) 'spellcheck': spellcheck,
            if (style != null) 'style': style,
            if (tabindex != null) 'tabindex': tabindex,
            if (title != null) 'title': title,
            if (href != null) 'href': href,
            if (target != null) 'target': target,
            if (rel != null) 'rel': rel,
            if (hreflang != null) 'hreflang': hreflang,
            if (type != null) 'type': type,
            ...?attributes,
          },
        );
}
